url: https://bglar.github.io
#baseurl: /bglar.github.io

# Site settings
title: Brian Ogollah Glar
email: bogolla4@gmail.com
description: "Brian Ogollah's alternate universe of awesomeness and ingenuity. `The future belongs to those who believe in the beauty of their dreams`. So have a peep into my ideas, I know you want to"


# # Team names, titles and social links
# people:
# - name: Brian Ogollah
#   pic: 1
#   position: Lead Designer
#   social:
#     - title: twitter
#       url: #
#     - title: facebook
#       url: #
#     - title: stack-overflow
#       url: #

# - name: Larry Parker
#   pic: 2
#   position: Lead Marketer
#   social:
#     - title: twitter
#       url: #
#     - title: facebook
#       url: #
#     - title: linkedin
#       url: #

# - name: Diana Petersen
#   pic: 3
#   position: Lead Developer
#   social:
#     - title: twitter
#       url: #
#     - title: facebook
#       url: #
#     - title: google-plus
#       url: #

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/brianglar
  - title: facebook
    url: https://www.facebook.com/bglar
  - title: stack-overflow
    url: http://stackoverflow.com/users/7206682/glar
  - title: github
    url: http://github.com/bglar

# Build settings
markdown: kramdown
permalink: pretty
