url: https://bglar.github.io
#baseurl: /bglar.github.io

# Site settings
title: Brian Ogollah Glar
email: bogolla4@gmail.com
description: "Brian Ogollah's alternate universe of awesomeness and ingenuity. `The future belongs to those who believe in the beauty of their dreams`. So have a peep into my ideas, I know you want to"

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/brianglar
  - title: facebook
    url: https://www.facebook.com/bglar
  - title: stack-overflow
    url: http://stackoverflow.com/users/7206682/glar
  - title: github
    url: http://github.com/bglar

# Build settings
markdown: kramdown
permalink: pretty
